### ISSUE TITLE
医渡云信息安全部提示

### ISSUE THREAD

**Issue by sevck** [kefanwu/api-autotest#1]
Hi 同学你好，我们检测你上传的代码中涉及医渡云内网相关域名，请及时删除，谢谢。

**Comment by kefanwu** [comment]
已删除

**Comment by kefanwu** [comment]
已删除




| |
吴可凡
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2023年03月04日 11:15，sevck 写道：

Hi 同学你好，我们检测你上传的代码中涉及医渡云内网相关域名，请及时删除，谢谢。
